// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDL2PXpScLKLmpsTlCHeL5qzrJ4NurarU',
    appId: '1:362509127087:web:ac571c96c67767725ab35a',
    messagingSenderId: '362509127087',
    projectId: 'flutter-booru',
    authDomain: 'flutter-booru.firebaseapp.com',
    storageBucket: 'flutter-booru.appspot.com',
    measurementId: 'G-GG3GC11JX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS4o7OuM1tyH4Czjal5vBmxqXYTpsE6pc',
    appId: '1:362509127087:android:42cb7dcd881108765ab35a',
    messagingSenderId: '362509127087',
    projectId: 'flutter-booru',
    storageBucket: 'flutter-booru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jVL8iOnEhxF374mCnc0Du9Z_L_8ob_w',
    appId: '1:362509127087:ios:5760896ff9eca9b45ab35a',
    messagingSenderId: '362509127087',
    projectId: 'flutter-booru',
    storageBucket: 'flutter-booru.appspot.com',
    iosClientId: '362509127087-vetmpa2g04bt2lqgv41fnmugdjqkjrue.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBooru',
  );
}
