name: flutter_booru_client

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_booru_core:
    path: packages/flutter_booru_core
  flutter_booru_application:
    path: packages/flutter_booru_application
  flutter_booru_firebase:
    path: packages/flutter_booru_firebase
  flutter_booru_home:
    path: packages/flutter_booru_home

dev_dependencies:
  dino_generator: ^1.0.0-pre.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
