name: pansy_sdk

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  pansy_sdk_protocols:
    path: ../pansy_sdk_protocols
  cryptography: ^2.0.5
  path_provider: ^2.0.11
