name: flutter_booru_monorepo
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^5.2.1
  lint: ^2.0.1
  melos: ^2.6.0
  index_generator: ^3.3.3

index_generator:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
  indexes:
    - name: flutter_booru_core
      path: packages/flutter_booru_core/lib

    - name: flutter_booru_home
      path: packages/flutter_booru_home/lib

    - name: flutter_booru_contents
      path: packages/flutter_booru_contents/lib
