name: flutter_booru_home

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../flutter_booru_core
  flutter_booru_content_page:
    path: ../flutter_booru_content_page
  flutter_booru_profile_page:
    path: ../flutter_booru_profile_page

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.3.2

flutter:
  uses-material-design: true
