name: flutter_booru_profile_page

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../flutter_booru_core
  flutter_booru_profile:
    path: ../flutter_booru_profile
  flutter_booru_account:
    path: ../flutter_booru_account
  flutter_booru_content:
    path: ../flutter_booru_content

  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4

  freezed: ^2.3.2

flutter:
  uses-material-design: true
