name: flutter_booru_account_firebase

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_account:
    path: ../../flutter_booru_account
  flutter_booru_core_firebase:
    path: ../flutter_booru_core_firebase

  firebase_auth: ^4.2.4
  firebase_storage: ^11.0.10

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4

flutter:
  uses-material-design: true
