name: flutter_booru_profile

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../flutter_booru_core
  flutter_booru_account:
    path: ../flutter_booru_account

  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  cross_file: ^0.3.3+4
  image_picker: ^0.8.6+1
  cached_network_image: ^3.2.3

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4

  json_serializable: ^6.6.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true
