name: flutter_booru

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../packages/flutter_booru_core
  flutter_booru_home:
    path: ../packages/flutter_booru_home

  cloud_firestore: ^4.0.2
  firebase_core: ^2.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  dino: ^1.0.0-pre.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  dino_generator: ^1.0.0-pre.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
