name: flutter_booru_content_firebase

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_content:
    path: ../../flutter_booru_content
  flutter_booru_core_firebase:
    path: ../flutter_booru_core_firebase

  image: ^4.0.12
  dio: ^4.0.6

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4

flutter:
  uses-material-design: true
