name: pansy_sdk_isar

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  pansy_sdk:
    path: ../pansy_sdk
  uuid: 3.0.7
  isar: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
