name: flutter_booru_core

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.2
  firebase_core: ^2.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  dino_flutter: ^1.0.0-pre.0
  dino: ^1.0.0-pre.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  dino_generator: ^1.0.0-pre.1

flutter:
  uses-material-design: true
