name: pansy_sdk_protocols

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  protobuf: ^2.1.0
  grpc: ^3.1.0

dev_dependencies:
  index_generator: ^3.3.3

index_generator:
  indexes:
    - path: lib
      include:
        - "src/**"
