name: flutter_booru_content

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../flutter_booru_core
  flutter_booru_account:
    path: ../flutter_booru_account
  flutter_booru_profile:
    path: ../flutter_booru_profile

  photo_view: ^0.14.0
  video_player: ^2.5.1
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  cross_file: ^0.3.3+2
  image_picker: ^0.8.6+1
  equatable: ^2.0.5
  intl: 0.17.0

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4

  json_serializable: ^6.5.4
  freezed: ^2.3.2

flutter:
  uses-material-design: true
