name: flutter_booru_content_favorite

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../flutter_booru_core
  flutter_booru_content:
    path: ../flutter_booru_content

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
