name: flutter_booru_core_firebase

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../../flutter_booru_core

  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.2
  firebase_storage: ^11.0.10

dev_dependencies:
  build_runner: ^2.3.3
  dino_generator: ^1.0.0-pre.4

flutter:
  uses-material-design: true
