name: flutter_booru_account

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../flutter_booru_core

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  dino_generator: ^1.0.0-pre.4

flutter:
  uses-material-design: true
