name: flutter_booru_firebase

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core_firebase:
    path: flutter_booru_core_firebase
  flutter_booru_content_firebase:
    path: flutter_booru_content_firebase
  flutter_booru_account_firebase:
    path: flutter_booru_account_firebase
  flutter_booru_profile_firebase:
    path: flutter_booru_profile_firebase

flutter:
  uses-material-design: true
