name: flutter_booru_application

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_booru_core:
    path: ../flutter_booru_core

flutter:
  uses-material-design: true
